version: '3.7'

services:
        web:
                build: 
                        context: .
                        dockerfile: Dockerfile
                command: gunicorn --bind 0.0.0.0:5000 python app:app
                ports:
                        - 5000:5000
                env_file:
                        - ./.env
